server:
  servlet:
    contextPath: /api

spring:
  application:
    name: users-api
# Pagination configuration 
  data:
    web:
      pageable:
        default-page-size: 20
# Datasource configuration
  datasource:
    url: "jdbc:postgresql://localhost:5432/users_db"
    username: "postgres"
    password: "password"

# Custom validation constraints
validation-constraints:
  user:
    required-age: 18

# Logger
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.github.malyshevhen: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: '.logs/users-api-dev.log'
